apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-autohealing
  labels:
    app: autoheal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: autoheal
  template:
    metadata:
      labels:
        app: autoheal
    spec:
      containers:
        - name: nginx
          image: nginx
